### PR TITLE
Small changes to lagrange multipliers tutorial

### PR DESCRIPTION
**Pull request by schnellerhase**
Noted some minor improvements while reading through the example.

Biggest change is the combining of the previously separate weak forms, this should make clearer how the blocks of the weak forms are formed in the code later on.

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
Thanks Paul.

I force pushed with a recent update from `main`, since `main` got broken earlier this week.
(I know that you got told never to force push in `dolfinx`, but I myself love linear history, so I am happy to force push on branches if that helps keeping that history).

I agree with your comment in the third commit that there is an inconsistency because I used to combine two unknowns in the first equation and leave the third unkown uncombined in the second equation.
However, I'd very much like that the inconsistency is solved the other way around: let's write three equations in a system. I think that is much closer to the latex description in the two other files in the same folder, and is exactly what is written in the code with the block formulation. Would you be willing to do that change? (If so, feel free to force push on the third commit :P)

I will add you to the `AUTHORS` file. Is there an email address that you want me to list there?
(Your commits are coming from `56360279+schnellerhase@users.noreply.github.com`, which is the email address that github automatically assigns. If you are using that email address for privacy concerns I simply won't list an email address in the file).

Thanks again,
Francesco

**Comment by schnellerhase** [comment]
Hey Francesco,

love the linear history style ;)

I added the three equation system as well. Might be good to keep the single line formulation in there as well, so I didn't replace it. Do you agree?

Regarding the email, yes exactly for privacy reasons. No email is just fine - thanks.

**Comment by schnellerhase** [comment]
PS: I couldn't get multi alignments to work with the latex `cases`. If this is the way to go I can update the other two examples to the same style.

**Comment by francesco-ballarin** [comment]
> Might be good to keep the single line formulation in there also (highlights better the compatibility condition that gets enforced), so I didn't replace it. Do you agree?

Agreed.

> If this is the way to go I can update the other two examples to the same style.

Yes, please do, if possible. At first glance I didn't like that getting rid of cases meant that there was no more a curly brace on the left of the system... but after all I don't expect anyone to misunderstand that those equations are coupled just because there is a brace missing :rofl: , and I agree that having a better alignment is beneficial for the reader.

Thanks!

**Pull request merged**
